jarToBehavior.set(TRI_ROSE_NEAR;
  .id, new TriRoseNear());
  jarToBehavior.set(TRISOLARIS_RUSD_NEAR;
  .id, new TrisolarisRusdNear());
  jarToBehavior.set(TRISOLARIS_LINEAR_NEAR;
  .id, new TrisolarisLinearNear());
  jarToBehavior.set(TRISOLARIS_SOLACE_NEAR;
  .id, new TrisolarisSolaceNear());
  jarToBehavior.set(TRISOLARIS_XNL_AURORA;
  .id, new TrisolarisXnlAurora());
  jarToBehavior.set(TRISOLARIS_GBA_USDT;
  .id, new TrisolarisGbaUsdt());
  jarToBehavior.set(TRISOLARIS_BBT_NEAR;
  .id, new TrisolarisBbtNear());
  jarToBehavior.set(TRISOLARIS_GBA_USDT;
  .id, new TrisolarisGbaUsdt());
  jarToBehavior.set(TRISOLARIS_USDC_SHITZU;
  .id, new TrisolarisUsdcShitzu());
  jarToBehavior.set(TRISOLARIS_GBA_USDT;
  .id, new TrisolarisGbaUsdt());
  jarToBehavior.set(TRISOLARIS_USDC_SHITZU;
  .id, new TrisolarisUsdcShitzu());
  jarToBehavior.set(NEARPAD_MODA_PAD;
  .id, new NearpadModaPad());
  jarToBehavior.set(NEARPAD_DAI_PAD;
  .id, new NearpadDaiPad());
  jarToBehavior.set(NEARPAD_PAD_AURORA;
  .id, new NearpadPadAurora());
  jarToBehavior.set(NEARPAD_PAD_ROSE;
  .id, new NearpadPadRose());
  jarToBehavior.set(NEARPAD_NEAR_ETH;
  .id, new NearpadNearEth());
  jarToBehavior.set(NEARPAD_NEAR_FRAX;
  .id, new NearpadNearFrax());
  jarToBehavior.set(NEARPAD_PAD_TRI;
  .id, new NearpadPadTri());
  jarToBehavior.set(WANNASWAP_WANNAX_STNEAR;
  .id, new WannaswapWannaxStnear());
  jarToBehavior.set(WANNASWAP_WANNAX_STNEAR;
  .id, new WannaswapWannaxStnear());
  